### ISSUE TITLE
No matlab engine found

### ISSUE THREAD

**Issue by harishprabhala** [jgamper/WholeSlideImageSampler#11]
I have pip installed wsisampler. But when I run the code, it says no Matlab engine found. How do I resolve this issue?

**Comment by jgamper** [comment]
Hi @harishprabhala ! You do not necessarily need matlab engine if you are working only with [openslide supported formats](https://openslide.org/formats/). However, if you are planning to work with jp2 whole slide images, then you will have to [set up matlab engine](https://www.mathworks.com/help/matlab/matlab_external/install-the-matlab-engine-for-python.html) yourself, and make it accessible for your python environment.
