### ISSUE TITLE
development / test OpenJP2 versus Openslide objects

### ISSUE THREAD

**Issue by jgamper** [jgamper/WholeSlideImageSampler#3]
Gotta start documenting the development somehow? Is there a way to keep goals that we would like to reach? 

Either way, it would be good to write unittest applied to one WSI that would be read by OpenJP2 versus Openslide, and compare the outputs (just to be sure), and also develop something like thumbnail for OpenJP2.

**Comment by Peter554** [comment]
It would be good to have some way of directly comparing results of jp2 and openslide formats. But is this possible? Can openjp2 also read openslide files for direct comparison?

For tests I think we need small unit-style tests (pytest https://docs.pytest.org/en/latest/ is good?) on individual functions and then demo notebooks for the overall process?

In terms of goals I think we want:

- a simple, uniform interface that enables patch extraction for both opeslide and jp2 images
- can handle annotations (binary and multilabel) is a few standard formats
- that is documented 
- and tested (as much as can be) 
- and isn't too slow!
- and also has minimal dependencies (and docs on how to to install them)

**Comment by jgamper** [comment]
Yes, we could take .tif image, and compare JP2Open versus openslide. 

For annotations, most of the annotations for jp2 images within the lab are .xml. Would be useful to have a script for that. Or is there something that I dont know?

In terms of minimal dependencies - matlab is quite a large dependency :-1: . But I would think whoever is going to use this software, will already have matlab license.

**Comment by jgamper** [comment]
- fully match OpenJP2 functionality with Openslide object
   - Thumbnail generation
- test OpenJP2 vs Openslide on tif
- write pytests to cover as much as possible
- create contribution.md
- add blur check when saving patches
- do something about .xml situation
- setup Travis CI with wget of data from google drive (is it possible?)
- docs

**set up project or milestones for all of that, to structure the path forward**
